// All site content lives here. index.html is a shell; script.js renders from this data.
//
// To add a project: drop the capture through `scripts/encode-video.sh <file> <slug>`, then add an
// entry to PROJECTS. Optional fields can be left out — empty sections are not rendered.
//
//   kind        'game' | 'tool'   (games go to the Games grid, tools to Tools & prototypes)
//   studio      key into STUDIOS
//   media       { video, poster, audio } or { image }; add fit: 'contain' for screenshots
//   facts       extra Inspector rows, e.g. { label: 'Installs', value: '1M+' }
//   links       { type: 'github' | 'npm' | 'releases' | 'play' | 'appstore' | 'itch' | 'download', url }
//   delisted    true when the store pages are gone; shown instead of dead store links

const STUDIOS = {
  joygame: { name: 'Joygame Publishing', short: 'Joygame' },
  flamingo: { name: 'Flamingo Game Studio', short: 'Flamingo' },
  ddog: { name: 'DDog Games', short: 'DDog' },
  flat: { name: 'Flat Games', short: 'Flat Games' },
}

const video = (slug, opts = {}) => ({
  video: `videos/${slug}.mp4`,
  poster: `videos/posters/${slug}.jpg`,
  ...opts,
})

const PROJECTS = [
  // ---------- Joygame Publishing ----------
  {
    slug: 'package-sort-3d',
    title: 'Package Sort! 3D',
    kind: 'game',
    studio: 'joygame',
    year: 2026,
    genre: 'Puzzle · Sorting',
    platforms: ['Android', 'iOS'],
    media: video('package-sort-3d', { audio: true }),
    tagline: 'Sort the boxes until every container holds four of a kind.',
    about:
      'A sorting puzzle where every container holds up to four boxes. Move boxes between containers, stack matching ones to move them together, and complete full sets to unlock the locked containers. Hidden boxes, covers and boosters keep the later levels interesting.',
    built: [
      'Core gameplay from the first commit: moving and stacking boxes, locked and hidden containers, covers, and the undo and shuffle boosters.',
      'A browser-based level editor for building and tuning levels outside of Unity.',
      "Built on the team's template project: VContainer, UniTask, event and query buses, and ordered SDK initialization.",
      'CI/CD on GitHub Actions: Android and iOS builds, deployment, and publishing to Google Play and the App Store.',
      'Integrated the shared live events module (Cocktail Bar, Egg Crack, Diggy and more) with its own analytics routing.',
      'Remote Config, AppsFlyer, Amplitude and AppLovin MAX ad revenue tracking.',
      'Localization with I2 Localization, including an iOS post-process build step.',
    ],
    stack: ['Unity 6', 'C#', 'VContainer', 'UniTask', 'Firebase', 'GitHub Actions', 'AppLovin MAX', 'I2 Localization'],
    links: [
      { type: 'play', url: 'https://play.google.com/store/apps/details?id=com.joygame.packagesort' },
      { type: 'appstore', url: 'https://apps.apple.com/us/app/package-sort-3d/id6758945992' },
    ],
  },

  {
    slug: 'coloring-book-ai',
    title: 'Coloring Book AI',
    kind: 'game',
    studio: 'joygame',
    year: 2025,
    genre: 'Color by number · Generative AI',
    platforms: ['Android', 'iOS'],
    facts: [
      { label: 'Published as', value: 'JLabs' },
      { label: 'Status', value: 'Pre-release (v0.0.2)' },
    ],
    media: {
      poster: 'videos/posters/coloring-book-ai.jpg',
      images: [
        { src: '1x/coloring-book-ai/01-home.jpg', caption: 'Home' },
        { src: '1x/coloring-book-ai/02-keywords.jpg', caption: 'Pick keywords' },
        { src: '1x/coloring-book-ai/03-prompt.jpg', caption: 'Generated prompt' },
        { src: '1x/coloring-book-ai/04-generated.jpg', caption: 'Generated artwork' },
        { src: '1x/coloring-book-ai/05-coloring.jpg', caption: 'Coloring' },
      ],
    },
    tagline: 'Turn a few keywords into your own color-by-number artwork.',
    about:
      'Pick a few keywords, get an AI-written prompt, and generate an image that is instantly turned into a numbered coloring page. Pan and pinch to zoom, pick a color from the palette, and tap the regions to fill them in, or use the bucket to fill every region of the selected color.',
    built: [
      'Learned Flutter for this project and built the app shell, onboarding, shop and credit economy in it.',
      'Embedded Unity inside the Flutter app and designed a typed JSON message bridge with an event bus: Flutter sends the generated image and painting commands, and Unity replies with processing progress, color palettes, paint progress and artwork collections.',
      'Image-to-coloring-page pipeline in Unity: downscale, K-means color quantization, Kuwahara filter, palette reduction, then connected-component labeling to find every paintable region.',
      'Made it fast enough for phones with Burst-compiled jobs: parallel K-means assignment, chunked Kuwahara filtering, and two-pass CCL with union-find.',
      'Small regions are merged into their best neighbor using a mix of color similarity, distance and size, so the page stays paintable.',
      'Each number is placed on the pixel closest to its region\'s centroid, so labels stay inside even irregular shapes; labels scale with zoom and are culled off-screen.',
      'Fills animate outward from the tapped point. Prompts come from GPT-4o mini and images from DALL·E 3, with both models switchable via Remote Config.',
      'Prototyped the algorithms first in pure Dart (including marching-squares border tracing to SVG) before moving them to Unity.',
    ],
    stack: ['Flutter', 'Dart', 'Unity', 'C#', 'Burst / Jobs', 'flutter_embed_unity', 'OpenAI API', 'Firebase'],
  },

  // ---------- Flamingo Game Studio ----------
  {
    slug: 'car-crash-3d',
    title: 'Car Crash 3D',
    kind: 'game',
    studio: 'flamingo',
    year: 2022,
    genre: 'Hyper-casual · Driving',
    platforms: ['Android'],
    delisted: true,
    media: video('car-crash-3d', { audio: true }),
    tagline: 'Survive the obstacle course in a car that dents for real.',
    about:
      'Drive through crushers, ramps and drops and keep your car in one piece long enough to reach the transporter at the end of the level.',
    built: [
      'Integrated a car physics package that deforms the mesh on impact.',
      'Damage carries over between sessions without saving any mesh data: impact forces above a minimum threshold are stored and re-applied on the next launch, which keeps save data tiny.',
    ],
    stack: ['Unity', 'Car physics', 'Mesh deformation'],
  },
  {
    slug: 'baby-boss-run',
    title: 'Baby Boss Run',
    kind: 'game',
    studio: 'flamingo',
    year: 2022,
    genre: 'Hyper-casual · Runner',
    platforms: ['Android'],
    delisted: true,
    media: video('baby-boss-run'),
    tagline: 'Collect babies, grow up and take over the baby company.',
    about:
      'A runner where every baby you collect makes you grow: earn the suit, the shoes and the tie, avoid whatever shrinks you back, and become the head of the baby company.',
    built: [
      'Built a level generation plugin on top of Curvy Splines so new levels could be laid out quickly.',
      'Used Unity Animation Rigging for the IK on the mechanical arm.',
    ],
    stack: ['Unity', 'Curvy Splines', 'Animation Rigging', 'Editor scripting'],
  },
  {
    slug: 'cube-puzzle-3d',
    title: 'Cube Puzzle 3D',
    kind: 'game',
    studio: 'flamingo',
    year: 2022,
    genre: 'Puzzle',
    platforms: ['Android'],
    delisted: true,
    media: video('cube-puzzle-3d'),
    tagline: 'Clear the outside of the cube to reveal the scene inside.',
    about:
      'Every cube hides a small diorama. Remove the tiles in the right order without getting stuck, and the view inside is revealed.',
    stack: ['Unity'],
  },
  {
    slug: 'hoarder-cleaner',
    title: 'Hoarder Cleaner',
    kind: 'game',
    studio: 'flamingo',
    genre: 'Hyper-casual · Cleaning',
    media: video('hoarder-cleaner', { audio: true }),
    tagline: "Clean up a hoarder's house, room by room, in any order.",
    about:
      'Scrub, vacuum and tidy every room of a cluttered house. Each level is a whole house, and the player decides which room to clean first.',
    built: [
      'Designed a non-linear level loop: a level is a set of rooms and the player chooses the order to play them in.',
      'Used Paint3D to wipe dirt off surfaces in real time.',
    ],
    stack: ['Unity', 'Paint3D'],
  },
  {
    slug: 'guess-song',
    title: 'Guess The Song 3D',
    kind: 'game',
    studio: 'flamingo',
    year: 2022,
    genre: 'Puzzle · Music',
    platforms: ['Android'],
    delisted: true,
    media: video('guess-song', { audio: true }),
    tagline: 'A music quiz: listen to the clip and guess the song.',
    about: 'A song plays and you work out which one it is. Get it right to move on to the next level.',
    stack: ['Unity', 'Sound analysis'],
  },
  {
    slug: 'skate-runner',
    title: 'Skate Runner',
    kind: 'game',
    studio: 'flamingo',
    genre: 'Hyper-casual · Racing',
    media: video('skate-runner'),
    tagline: 'Build momentum and race other skaters to the finish.',
    about:
      'A momentum-based race against other skaters down a winding track. The run ends with a launch across the multiplier zone, and the further you fly, the bigger the reward.',
    built: [
      'Built the first iteration of the spline-based level editor that later became the Curvy Splines plugin.',
      'Spline road meshes can be split into multiple parts to create gaps, and coins and road ends are placed automatically.',
    ],
    stack: ['Unity', 'Splines', 'Shader Graph'],
  },

  // ---------- DDog Games ----------
  {
    slug: 'restock',
    title: 'Restock!',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Puzzle · ASMR',
    platforms: ['Android'],
    delisted: true,
    facts: [
      { label: 'Publisher', value: 'Yso Corp' },
      { label: 'Installs', value: '1M+ on Google Play' },
    ],
    media: video('restock', { audio: true }),
    tagline: 'Unpack the groceries and fit every item into the fridge.',
    about:
      'A relaxing, ASMR-style organising puzzle: unpack the shopping basket and fit every item neatly into the fridge shelves. Published by Yso Corp, it passed a million installs on Google Play.',
    stack: ['Unity', 'Prefab Variants', 'Blend Shapes'],
  },
  {
    slug: 'draw-clone',
    title: 'Draw Clone',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Arcade',
    platforms: ['Android'],
    delisted: true,
    media: video('draw-clone'),
    tagline: 'Draw a path, clone your army and take the enemy base.',
    about:
      'Draw the route for your characters, lead them through multiplier gates to clone them, and overwhelm the enemy base at the end.',
    built: ['Character navigation built on Unity NavMesh Components.'],
    stack: ['Unity', 'NavMesh Components'],
  },
  {
    slug: 'clone-balls',
    title: 'Clone Balls',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Arcade',
    platforms: ['Android'],
    delisted: true,
    media: video('clone-balls'),
    tagline: 'Multiply your balls through gates and smash the picture.',
    about:
      'Shoot balls through multiplier gates and smash the pixel-art blocks. Carry as many balls as you can into the next stage.',
    built: ['Used MaterialPropertyBlocks to colour hundreds of blocks individually without creating new materials.'],
    stack: ['Unity', 'MaterialPropertyBlocks'],
  },
  {
    slug: 'chef-sweetie',
    title: 'Chef Sweetie',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Hyper-casual · Runner',
    platforms: ['Android'],
    delisted: true,
    media: video('chef-sweetie'),
    tagline: 'Collect knives and slice every sweet on the way.',
    about:
      'Run through a candy world collecting knives, slice every sweet in your path for points, and reach the end of the level.',
    built: ['Real-time mesh slicing with the BzKovSoft slicer.'],
    stack: ['Unity', 'Prefab Variants', 'BzKovSoft'],
  },
  {
    slug: 'block-stacker',
    title: 'Block Stacker',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Hyper-casual · Runner',
    platforms: ['Android', 'iOS'],
    delisted: true,
    media: video('block-stacker'),
    tagline: 'Change the size of your arms to grab blocks and build bridges.',
    about:
      'A stacking runner with a twist: widen or narrow your arms to collect blocks, then spend them to build bridges over the gaps.',
    built: ['Arm size driven by blend shapes.', 'Tracks laid out with Curvy Splines.'],
    stack: ['Unity', 'Blend Shapes', 'Curvy Splines'],
  },
  {
    slug: 'magic-master-3d',
    title: 'Magic Master 3D',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Arcade · Runner',
    platforms: ['Android', 'iOS'],
    delisted: true,
    media: video('magic-master-3d', { audio: true }),
    tagline: 'Pick the right spell and defeat every opponent.',
    about: 'Become the greatest mage: run the path, switch between spells and defeat the opponents waiting along the way.',
    built: ['Paths laid out with Curvy Splines.'],
    stack: ['Unity', 'Curvy Splines'],
  },
  {
    slug: 'magic-art-3d',
    title: 'Magic Art 3D',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Casual · Art',
    platforms: ['iOS'],
    delisted: true,
    media: video('magic-art-3d'),
    tagline: 'Complete painting orders, sell the art and earn money.',
    about: 'Customers come in with an order; create the painting they asked for, sell it and earn money.',
    built: ['Orders and paintings are defined as ScriptableObjects.'],
    stack: ['Unity', 'ScriptableObjects'],
  },
  {
    slug: 'agent-rubberhand',
    title: 'Agent Rubberhand',
    kind: 'game',
    studio: 'ddog',
    year: 2021,
    genre: 'Action',
    platforms: ['iOS'],
    delisted: true,
    media: video('agent-rubberhand'),
    tagline: 'Stretch, grab, smash, shoot and punch.',
    about: 'Drag your stretchy body around the level, smash everything, grab weapons and take down the guards.',
    built: ['Stretchy rubber limbs simulated with Obi Rope.'],
    stack: ['Unity', 'Obi Rope'],
  },
  {
    slug: 'worlds-hardest-run',
    title: 'Worlds Hardest Run',
    kind: 'game',
    studio: 'ddog',
    year: 2020,
    genre: 'Hyper-casual',
    platforms: ['iOS'],
    delisted: true,
    media: video('worlds-hardest-run'),
    tagline: 'Bend the path in real time to reach the finish.',
    about: 'The road is a spline you drag while running. Reshape it on the fly to get past the obstacles and reach the finish.',
    built: ['Runtime spline editing with Curvy Splines: the player drags the path while the character runs along it.'],
    stack: ['Unity', 'Curvy Splines'],
  },
  {
    slug: 'jelly-mania-blast',
    title: 'Jelly Mania Blast',
    kind: 'game',
    studio: 'ddog',
    year: 2020,
    genre: 'Puzzle',
    platforms: ['iOS'],
    delisted: true,
    media: video('jelly-mania-blast', { audio: true }),
    tagline: 'Pop the jellies strategically to complete your mission.',
    about: "Pop groups of coloured jellies in the jar to complete each level's mission within a limited number of moves.",
    built: ['Jellies rendered as metaballs so neighbouring blobs merge into one soft shape.'],
    stack: ['Unity', 'Metaballs'],
  },

  // ---------- Flat Games ----------
  {
    slug: 'wheel-smash-3d',
    title: 'Wheel Smash 3D!',
    kind: 'game',
    studio: 'flat',
    year: 2020,
    genre: 'Hyper-casual',
    platforms: ['iOS'],
    delisted: true,
    media: video('wheel-smash-3d'),
    tagline: 'Crush objects under a giant wheel to win subscribers.',
    about:
      'Hold to roll a giant wheel over watermelons, piggy banks and rubber chickens. Every smash wins subscribers for your channel.',
    built: ['Object deformation with VertexMotion.'],
    stack: ['Unity', 'VertexMotion'],
  },
  {
    slug: 'animals-and-puzzles',
    title: 'Animals and Puzzles',
    kind: 'game',
    studio: 'flat',
    year: 2020,
    genre: 'Puzzle',
    platforms: ['Android'],
    media: video('animals-and-puzzles', { audio: false }),
    tagline: 'Free the animals by solving sudoku-style block puzzles.',
    about: 'Place block pieces on the grid following sudoku rules to free the caged animals.',
    stack: ['Unity', 'C#'],
    links: [
      { type: 'github', url: 'https://github.com/kubilayege/Untitled-Puzzle-Game' },
      { type: 'download', url: 'https://github.com/kubilayege/Untitled-Puzzle-Game/releases/tag/v0.0.15' },
    ],
  },

  // ---------- Tools & prototypes ----------
  {
    slug: 'nudge',
    title: 'Nudge',
    kind: 'tool',
    studio: 'joygame',
    year: 2026,
    genre: 'Team workspace · Agents',
    facts: [
      { label: 'Used by', value: 'Joygame teams' },
      { label: 'Agent package', value: '@euqns/nudge-mcp, 68 releases' },
    ],
    media: {
      wide: true,
      poster: 'videos/posters/nudge.jpg',
      images: [
        { src: '1x/nudge/01-board.jpg', caption: 'Board' },
        { src: '1x/nudge/02-canvas.jpg', caption: 'Canvas' },
        { src: '1x/nudge/03-docs.jpg', caption: 'Docs' },
        { src: '1x/nudge/04-gantt.jpg', caption: 'Gantt' },
        { src: '1x/nudge/05-pulse.jpg', caption: 'Pulse' },
        { src: '1x/nudge/06-agent-run.jpg', caption: 'Agent run' },
        { src: '1x/nudge/07-runners.jpg', caption: 'Self-hosted runners' },
      ],
    },
    tagline: 'Tasks, docs, canvas and coding agents in one team workspace.',
    about:
      'A team workspace I built for Joygame: kanban boards, docs, a brainstorming canvas, a Gantt timeline and analytics, with real-time collaboration. Cards can be handed to coding agents that run on our own machines, so a task goes from idea to pull request without leaving the board. Screenshots use the built-in demo data.',
    built: [
      'Task management: kanban with labels, priorities and dependencies, rich card pages with inline comments and mentions, My Tasks, an Inbox, web push, and ⌘K search.',
      'Docs: a per-board doc shelf of pages, sheets, Figma, video and git links and uploaded files, with a block editor built on Tiptap.',
      'Canvas: an infinite brainstorming surface with stickies, shapes, icons, sections and live references to cards, docs and boards, connected by labelled edges.',
      'Planning and insight: a Gantt timeline with drag-to-schedule and dependency arrows, and Pulse analytics for what shipped, per board and across the team.',
      'Software factory: self-hosted runners turn cards into Claude Code, Codex or Cursor jobs on our own machines. Runs can be pinned to a machine, run concurrently, stream progress, take steering mid-run, and report the summary, PR, CI pipelines and cost back on the card.',
      'Runners heartbeat, install as login services and update themselves from npm, and an Agent View shows every running, queued and waiting job across the workspace.',
      'An MCP server, both remote over HTTP and local over stdio, lets agents drive the boards as the signed-in user with hashed, revocable personal tokens.',
      'Local-first: boards work offline in the browser, then sync through Convex in real time once promoted to the cloud, with Google sign-in limited to the company domain.',
    ],
    stack: ['React', 'TypeScript', 'Convex', 'Tiptap', 'dnd-kit', 'Dexie', 'MCP', 'AWS S3', 'Vercel'],
    links: [{ type: 'npm', url: 'https://www.npmjs.com/package/@euqns/nudge-mcp' }],
  },
  {
    slug: 'funjitsu-ci-cd',
    title: 'Funjitsu CI/CD',
    kind: 'tool',
    studio: 'joygame',
    year: 2026,
    genre: 'Build pipeline',
    facts: [{ label: 'In use by', value: '14 game projects' }],
    media: { image: '1x/funjitsu-dashboard.jpg', poster: 'videos/posters/funjitsu-dashboard.jpg', wide: true },
    tagline: 'One dashboard to build, sign and ship every Unity game to the stores.',
    about:
      "Joygame's internal build system. The team adds a Unity project, installs the pipeline into its repo, and triggers Android and iOS builds that go all the way to Google Play and TestFlight. Game names and versions are blurred in the screenshot.",
    built: [
      'Next.js dashboard with GitHub token sign-in: add projects, install the pipeline into a repo on any branch, trigger builds and browse build history.',
      'Reusable GitHub Actions workflows: Android builds with game-ci, and iOS in two phases (Xcode project on Linux, archive and export on a self-hosted macOS runner).',
      'Publishing to Google Play and the App Store, store version sync, and a guard against reusing built version numbers.',
      'Signing setup from the dashboard: keystore alias detection, certificate generation, and store credentials stored as org-level secrets.',
      'Build artifacts and a build manifest on Cloudflare R2, with the project registry in MongoDB Atlas.',
      'Ask AI, build analysis and changelogs through a local AI companion (Claude Code, Cursor or Codex), with an OpenRouter fallback.',
      'Preflight checks, shader-cache invalidation, Unity editor installs and Android native symbol uploads to keep builds reliable.',
    ],
    stack: ['GitHub Actions', 'game-ci', 'Next.js', 'TypeScript', 'MongoDB Atlas', 'Cloudflare R2', 'Octokit'],
  },
  {
    slug: 'unity-behavior-tree-mcp',
    title: 'Unity Behavior Tree MCP',
    kind: 'tool',
    year: 2026,
    genre: 'AI tooling · MCP',
    facts: [
      { label: 'Type', value: 'Personal · open source (MIT)' },
      { label: 'Published', value: 'npm, v0.1.1' },
    ],
    media: { image: '1x/unity-behavior-tree-mcp.jpg', poster: 'videos/posters/unity-behavior-tree-mcp.jpg' },
    tagline: 'Let AI agents build Unity Behavior Graphs directly in the Editor.',
    about:
      'An MCP server that gives AI agents like Claude Code and Cursor typed tools for authoring Unity Behavior Graph assets: create graphs, add and wire nodes, set node fields, and manage blackboard variables. Unity stays the source of truth, and the runtime graph is rebuilt after every change.',
    built: [
      'TypeScript MCP server with 17 typed tools (zod schemas) across discovery, graphs, nodes and blackboard, talking to the client over stdio.',
      'Unity Editor bridge as a UPM package: an HTTP listener on localhost that starts with the Editor and runs every request on the main thread.',
      "Unity Behavior keeps most of its authoring API internal, so the bridge drives BehaviorAuthoringGraph, the node registry and runtime graph rebuilds through reflection.",
      'Node types come live from the project, so custom [NodeDescription] actions show up for the agent right after Unity recompiles.',
      'Node fields take either literal values or a link to a blackboard variable, with typed variables including Vector3, GameObject and project enums.',
      'Published to npm, installable with one claude mcp add command.',
    ],
    stack: ['TypeScript', 'MCP SDK', 'zod', 'Unity', 'C#', 'Unity Behavior', 'Reflection'],
    links: [
      { type: 'github', url: 'https://github.com/kubilayege/unity-behavior-tree-mcp' },
      { type: 'npm', url: 'https://www.npmjs.com/package/@euqns/unity-behavior-tree-mcp' },
    ],
  },
  {
    slug: 'usagebar',
    title: 'UsageBar',
    kind: 'tool',
    year: 2026,
    genre: 'macOS app · Side project',
    platforms: ['macOS'],
    facts: [
      { label: 'Type', value: 'Personal · open source' },
      { label: 'Releases', value: 'v1.7.2, 21 releases' },
    ],
    media: {
      poster: 'videos/posters/usagebar.jpg',
      images: [
        { src: '1x/usagebar/01-popover.jpg', caption: 'Menu bar popup' },
        { src: '1x/usagebar/02-receipt.jpg', caption: 'Work receipt' },
        { src: '1x/usagebar/03-worklog.jpg', caption: 'Work Log' },
        { src: '1x/usagebar/04-dashboard.jpg', caption: 'Dashboard' },
      ],
    },
    tagline: 'Watches your AI agent quotas, and prints a receipt of what they worked on.',
    about:
      'A fun side project: a native macOS menu bar app that tracks Claude Code, Codex, Cursor and OpenCode quotas in one place and answers "when do I get cut off?". Its favourite trick is the work receipt: a till-style summary of what your agents did today, ready to paste into a standup or a timesheet. Everything stays on the Mac, with no accounts or telemetry. Screenshots use demo data and made-up projects.',
    built: [
      'Work receipts: a daily, weekly or monthly receipt of what the agents worked on, grouped by project, with active time, files touched and an optional token and cost line. Copy it in one click, or export it as text, Markdown, CSV or a receipt image.',
      'Work Log page behind it: a per-project timeline of every minute an agent was working, sessions named by their own titles, and a hide switch that keeps client or NDA projects out of every export. Only timestamps, titles, file paths and token counts are read; prompts and code are never stored.',
      'One meter per 5-hour, weekly and monthly window: the fill is usage, a needle marks how much of the window has passed, and a hatched run shows where the current pace lands at reset.',
      'A runway headline and per-provider verdicts (At limit, Out in 38m, Tight, On pace), plus notifications at 75, 90 and 100%.',
      'Several Claude and Codex accounts side by side, overage tracking, service status chips, and automatic back-off when a vendor rate-limits the usage endpoint.',
      'Shipped through GitHub Actions: a manually dispatched workflow runs the regression tests, builds the app bundle and DMG, signs a Sparkle update, and publishes the GitHub release that the in-app updater picks up.',
    ],
    stack: ['Swift', 'SwiftUI', 'AppKit', 'Sparkle', 'GitHub Actions', 'SQLite'],
    links: [
      { type: 'github', url: 'https://github.com/kubilayege/UsageBar' },
      { type: 'releases', url: 'https://github.com/kubilayege/UsageBar/releases' },
    ],
  },
  {
    slug: 'cloud-services-app',
    title: 'Unity Cloud Services App',
    kind: 'tool',
    studio: 'flamingo',
    year: 2023,
    genre: 'Backend · Live services',
    media: video('cloud-services-app'),
    tagline: 'A secure watch-and-earn app with a server-authoritative shop.',
    about:
      'A watch-and-earn app where players earn currency and spend it in a shop. Balances are checked on the server, so rewards cannot be faked on the client.',
    built: [
      'Player Authentication, Economy, Inventory and Remote Config from Unity Gaming Services.',
      'Cloud Code modules in .NET validate balances against a PostgreSQL database on Amazon RDS.',
      'Content delivered with Cloud Content Delivery and Addressables.',
      'Dependency injection with VContainer.',
    ],
    stack: ['Unity', 'Unity Gaming Services', 'Cloud Code', '.NET', 'Amazon RDS', 'PostgreSQL', 'VContainer'],
    links: [{ type: 'github', url: 'https://github.com/kubilayege/Unity-Cloud-Services' }],
  },
  {
    slug: 'multiplayer-prototype',
    title: 'Multiplayer Prototype',
    kind: 'tool',
    studio: 'flamingo',
    year: 2023,
    genre: 'Prototype · Networking',
    platforms: ['PC'],
    media: video('multiplayer-prototype', { wide: true }),
    tagline: 'A multiplayer party game prototype on Photon Fusion and Steam.',
    about:
      'A party game prototype built to find the right networking stack. We tried several solutions and settled on Photon Fusion with Steamworks.NET.',
    built: [
      'Client-side prediction, reconciliation and interpolation for precise movement and collisions.',
      'Steam integration through Steamworks.NET.',
      'Dependency injection with VContainer.',
    ],
    stack: ['Unity', 'Photon Fusion', 'Steamworks.NET', 'VContainer'],
    links: [{ type: 'github', url: 'https://github.com/kubilayege/MP-Prototype' }],
  },
  {
    slug: 'roguelike-prototype',
    title: 'Roguelike Prototype',
    kind: 'tool',
    studio: 'flamingo',
    year: 2023,
    genre: 'Prototype · Action',
    media: video('roguelike-prototype'),
    tagline: 'Different weapons, procedurally generated levels.',
    about: 'A top-down roguelike where the player can wield different weapons through seeded, procedurally generated levels.',
    built: [
      'Seeded procedural level generation with Dungeon Architect.',
      'Weapon attacks find their targets with physics casts.',
      'Combo attacks designed in the custom node graph editor.',
    ],
    stack: ['Unity', 'Dungeon Architect', 'GraphView'],
    links: [{ type: 'github', url: 'https://github.com/kubilayege/skill-cast-so' }],
  },
  {
    slug: 'node-graph-editor',
    title: 'Node Graph Editor',
    kind: 'tool',
    studio: 'flamingo',
    year: 2023,
    genre: 'Editor tooling',
    media: { image: '1x/ComboGraph.png', fit: 'contain' },
    tagline: 'A generic node graph editor, extended into a combo designer.',
    about:
      'A reusable graph editor library for the Unity editor, built for the roguelike project. We extended it into a Combo Graph for designing combo attacks for different weapon types.',
    built: [
      'Generic, extensible graph library on GraphView and UI Elements.',
      'Combo Graph with a split-view node editor for designing weapon combos.',
    ],
    stack: ['Unity', 'GraphView', 'UI Elements', 'Editor scripting'],
    links: [{ type: 'github', url: 'https://github.com/kubilayege/Generic-Graph-Editor' }],
  },
  {
    slug: 'private-package-registry',
    title: 'Private Unity Package Registry',
    kind: 'tool',
    studio: 'flamingo',
    genre: 'Infrastructure',
    media: { image: '1x/fupm.png', fit: 'contain' },
    tagline: "The studio's shared code, shipped as Unity packages.",
    about:
      'A private package registry so every project could pull the same shared code through the Unity Package Manager instead of copying it between projects.',
    built: [
      'Private registry with Verdaccio, hosted on Amazon EC2.',
      'Common packages for the developers to use across games.',
      'Project templates defined as bundles of packages.',
    ],
    stack: ['Unity', 'UPM', 'Verdaccio', 'AWS EC2'],
  },
  {
    slug: 'curvy-splines-editor',
    title: 'Curvy Splines Level Editor',
    kind: 'tool',
    studio: 'flamingo',
    year: 2023,
    genre: 'Editor tooling',
    media: video('curvy-splines-editor', { fit: 'contain', wide: true }),
    tagline: 'A non-destructive level editor for mobile runner games.',
    about:
      'A level editor plugin built on Curvy Splines for mobile runner levels. Roads are generated from the spline and can be edited at any time without losing work.',
    built: ['Road Generator and Road Parts for building levels non-destructively.', 'Built on Curvy Splines 7.'],
    stack: ['Unity', 'Curvy Splines', 'Editor scripting'],
    links: [{ type: 'github', url: 'https://github.com/kubilayege/CurvySplinesPlugin' }],
  },
]

// What I work on at Joygame — shown in the "Now" section.
const NOW = [
  {
    label: 'Teams',
    title: 'Live Games and New Games',
    text: 'I work with both teams: supporting games that are already live and building new ones from the ground up.',
    tags: ['Unity', 'C#'],
  },
  {
    label: 'CI/CD',
    title: 'Automated build pipelines',
    text: "Set up CI/CD so builds are produced automatically and the same way every time, instead of being exported by hand from someone's editor.",
    tags: ['CI/CD', 'Build automation'],
  },
  {
    label: 'Foundations',
    title: 'The template project',
    text: 'Built the template project the team uses as the starting point for every new game. Shared foundations are solved once, so new projects start on gameplay.',
    tags: ['Project architecture', 'Unity'],
  },
  {
    label: 'Agents',
    title: 'A software factory for the team',
    text: 'Self-hosted runners that pick up tasks from the board and hand them to Claude Code, Codex or Cursor, with the result coming back as a pull request on the card.',
    tags: ['Coding agents', 'MCP', 'Automation'],
  },
  {
    label: 'Tooling',
    title: 'Internal tools, factory-style',
    text: 'Tools the team runs on, like Nudge for tasks, docs and agents, and Funjitsu for building and shipping every game. Standardized, reusable and automated instead of one-off scripts.',
    tags: ['Internal tooling', 'Automation'],
  },
  {
    label: 'AI',
    title: 'AI-assisted development',
    text: 'I have built in-depth expertise in AI-assisted software development and use it daily to help the team ship faster and more consistently.',
    tags: ['AI-assisted development'],
  },
]

const EXPERIENCE = [
  {
    studio: 'joygame',
    title: 'Game Developer',
    when: '03/2024 — Present',
    where: 'Istanbul',
    points: [
      'Worked on both the Live Games and New Games teams',
      'Set up CI/CD and automated build pipelines',
      'Built a comprehensive template project the team uses as the starting point for new games',
      'Built team tools beyond the games: the Nudge workspace and the Funjitsu build dashboard',
      'Developed internal tools with a software factory mindset: standardized, reusable and automated workflows',
      'Built in-depth expertise in AI-assisted software development and applied it in daily work',
    ],
    jump: '#now',
  },
  {
    studio: 'flamingo',
    title: 'Game Developer',
    when: '11/2021 — 01/2024',
    where: 'Remote',
    points: [
      'Developed hyper-casual games',
      'Custom private Unity package registry',
      'Editor tools for level design',
      'Multiplayer game systems',
      'Unity cloud services',
      'Amazon EC2 and RDS systems',
    ],
  },
  {
    studio: 'ddog',
    title: 'Game Developer',
    when: '11/2020 — 10/2021',
    where: 'Remote',
    points: ['Developed around 10 hyper-casual games for the company', 'Software architecture', 'SOLID practices', 'Clean code'],
  },
  {
    studio: 'flat',
    title: 'Game Developer',
    when: '09/2019 — 05/2020',
    where: 'Remote',
    points: ['Developed a hyper-casual and a puzzle game for the company'],
  },
  {
    org: 'Karadeniz Technical University',
    title: 'Computer Engineering',
    when: 'Graduated 07/2020',
    where: 'Trabzon',
    points: [
      'Studied computer science and programming',
      'Held game development classes for fellow students, teaching Unity',
      'Graduation project: benchmarked Unity DOTS against MonoBehaviour',
    ],
  },
]

const SKILLS = [
  'Unity',
  'C#',
  '.NET',
  'Firebase',
  'TypeScript / React',
  'Swift',
  'MCP & agent tooling',
  'CI/CD & build pipelines',
  'AI-assisted development',
  'Internal tooling',
  'AWS',
  'Software architecture',
  'Software testing',
  'SDLC',
  'Networking',
  'OOP',
]

const LANGUAGES = ['English', 'Turkish']
